# Generated by Django 5.0.1 on 2024-01-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='return_devolucao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
