# Generated by Django 5.0.1 on 2024-01-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0002_produto_return_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='ordenado_por',
            field=models.CharField(default='SeuValorPadrão', max_length=200),
        ),
    ]
