# Generated by Django 5.0.1 on 2024-01-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0003_pedido_order_ordenado_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido_order',
            old_name='Carro',
            new_name='carro',
        ),
    ]
