# Generated by Django 5.2.4 on 2025-07-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0006_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_order',
            name='pedido_status',
            field=models.CharField(choices=[('Pedido Recebido', 'Pedido Recebido'), ('Pedido Processando', 'Pedido Processando'), ('Pedido Caminho', 'Pedido Caminho'), ('Pedido Completado', 'Pedido Completado'), ('Pedido Cancelado', 'Pedido Cancelado')], default='Pedido Processando', max_length=50),
        ),
    ]
