# Generated by Django 5.2.4 on 2025-07-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0007_alter_pedido_order_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_order',
            name='ordenado_por',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
