# Generated by Django 5.2.4 on 2025-07-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0008_alter_pedido_order_ordenado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_order',
            name='ordenado_por',
            field=models.CharField(max_length=200),
        ),
    ]
